networks:
  balance-dev:
    name: balance-dev
    external: false

services:
  balance-dev:
    container_name: balance-dev
    build:
      context: .
      dockerfile: docker/development/dockerfile
    env_file:
      - .env
    develop:
      watch:
        - path: ./config
          action: sync
          target: /var/www/html/config
        - path: ./resources
          action: sync
          target: /var/www/html/resources
        - path: ./routes
          action: sync
          target: /var/www/html/routes
        - path: ./tests
          action: sync
          target: /var/www/html/tests
    volumes:
      # Folders with auto-creation of files
      - ./storage/:/var/www/html/storage/
      - ./database/:/var/www/html/database/
      - ./app/:/var/www/html/app/
      # Composer and Node.js packages
      - ./vite.config.js:/var/www/html/vite.config.js
      - ./package.json:/var/www/html/package.json
      - ./package-lock.json:/var/www/html/package-lock.json
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
    ports:
      - "9092:80"
      - "5173:5173"
    networks:
      - balance-dev
    extra_hosts:
      - "host.docker.internal:host-gateway"
