# -----------------------------------
# Build Front-end
# -----------------------------------
FROM node:24.11.1-alpine3.22 AS frontend-builder
WORKDIR /var/www

# Copy Package File and do an install
COPY . .
RUN npm install

CMD ["npm", "run", "dev"]
